name: Pack application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx webpack

      - name: Set git credentials
        run: |
          git config --global user.name 'Workflow'
          git config --global user.email 'mailservice@robko.cz'

      - name: Upgrade version
        run: yarn version --patch --no-git-tag-version

      - name: Set version variable
        # source (edited) https://gist.github.com/DarrenN/8c6a5b969481725a4413?permalink_comment_id=3194363#gistcomment-3194363
        run: |
          echo "PACKAGE_VERSION<<EOF" >> $GITHUB_ENV
          sed -nr 's/^\s*\"version": "([0-9]{1,}\.[0-9]{1,}.*)",$/\1/p' package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Commit build output
        run: |
          git commit -am "v$PACKAGE_VERSION [skip ci]"
          git tag v$PACKAGE_VERSION

      - name: Push commit and tag
        run: |
          git push origin
          git push origin --tags
