name: Pack application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Build
      run: |
        npm install
        npx webpack
        
    - name: Commit build output
      run: |
          git config --global user.name 'Wordflow'
          git config --global user.email 'mailservice@robko.cz'
          git commit -am "Wordflow - added build output [skip ci]"
          git push
